Update maven-build.yaml
Signed-off-by: Shivam Rajesh Gupta <56411166+shivamg9@users.noreply.github.com>

diff --git a/.github/workflows/maven-build.yaml b/.github/workflows/maven-build.yaml
--- a/.github/workflows/maven-build.yaml
+++ b/.github/workflows/maven-build.yaml
@@ -85,12 +85,20 @@ jobs:
               echo "Warning: ARTIFACT $ARTIFACT not found"
             fi
           done
-     
+
+    - name: Check if ZIP file exists
+      run: |
+        ls -al
+        if [ ! -f ${{ inputs.BUILD_ARTIFACT }}.zip ]; then
+          echo "❌ ERROR: ${{ inputs.BUILD_ARTIFACT }}.zip not found!"
+          exit 1
+        fi
+        
     - name: Upload the springboot jars
       if: ${{ !contains(github.ref, 'master') || !contains(github.ref, 'main') }}
       uses: actions/upload-artifact@v4
       with:
         name: ${{ inputs.BUILD_ARTIFACT }}
-        path: ./${{ inputs.BUILD_ARTIFACT }}.zip
+        path: "**/${{ inputs.BUILD_ARTIFACT }}.zip"
 
   
